### ISSUE TITLE
Entering optional information only does not throw error

### ISSUE THREAD

**Issue by MBROQ** [joroq/CredersiVendCustomers#3]
**Describe the bug**
When entering only the optional information when making a customer on the console, still makes a customer. 

**To Reproduce**
1. Start the program
2. Enter 'Add' in the prompt section
3. Wait for program to prompt with inputs
4. Only insert optional address line 2 and 3
5. Creates customer

**Expected behavior**
Throw and exception and prompt to add information 

**Screenshots**
![image](https://user-images.githubusercontent.com/124673013/226915644-be11446b-3d55-462e-a021-c5fd32b6fa45.png)
![image](https://user-images.githubusercontent.com/124673013/226915734-f9a24e3d-c802-4abd-b18c-c295754c6c4c.png)

**Desktop (please complete the following information):**
 -OS: Windows_NT x64 10.0.22000

**Additional context**

**Comment by joroq** [comment]
Duplicate report - see CVC-NT-20
