### ISSUE TITLE
Making a new customer with no information, still makes an instance.

### ISSUE THREAD

**Issue by MBROQ** [joroq/CredersiVendCustomers#4]
**Describe the bug**
When making a new customer, when you input no information, the program still makes a customer ID

**To Reproduce**
1. Enter 'Add' into the prompt section
2. Wait for program to prompt to add input
3. Enter no information and progress through options
4. Customer ID will be made 

**Expected behavior**
Expect error and prompted to input information.

**Screenshots**
![image](https://user-images.githubusercontent.com/124673013/226921202-53ad722b-3463-434d-b338-0370a8fdac9b.png)
![image](https://user-images.githubusercontent.com/124673013/226923139-4fe96dc8-e621-4573-ab8f-6adea8eab8e7.png)

**Desktop (please complete the following information):**
 -OS: Windows_NT x64 10.0.22000

**Comment by joroq** [comment]
Duplicate report - see CVC-NT-021
